name: Validate and merge PR

on:
  issue_comment:
    types: [created]

jobs:
  do_merge:
    runs-on: ubuntu-20.04
    if: contains(github.event.comment.body, '/mergeOnGreen')
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          architecture: x64
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.MERGEBOT_TOKEN }}

      - name: Setup committer id
        run: |
          git config --global user.email "pytorchmergebot@users.noreply.github.com"
          git config --global user.name "PyTorch MergeBot"
      - name: Merge PR
        env:
          GITHUB_TOKEN: ${{ secrets.MERGEBOT_TOKEN }}
          PR_NUM: 6
          GH_RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          FORCE: "false"
          ON_GREEN: "true"
        run: |
          python3 .github/scripts/trymerge.py --on-green "${PR_NUM}"
